### ISSUE TITLE
Block nonvoting members from entering site 

### ISSUE THREAD

**Issue by RebeccaSyria** [ComputerScienceHouse/vote2020#19]
We can't have frosh look at the votes during 10 weeks, send them to an error page

**Comment by mxmeinhold** [comment]
This should do filtering similar to how [conditional counts voting members](https://github.com/ComputerScienceHouse/conditional/blob/055a2e705657167f981c4e9ed98715673bc715c8/conditional/util/member.py#L30-L36). Note that conditional does it a little weirdly with checking its own db. This probably should be a check of 
```python
def user_is_voting(user):
	non_voting groups = { '10weeks', 'fall_coop' if is_fall else 'spring_coop'}
	return 'active' in user.groups and not any(map(lambda group: group in user.groups, non_voting_groups))
```
but... not in python.

You will need to check if it's currently fall, or hard code it to fall_coop for the time being.
